# Generated by Django 5.1.3 on 2024-11-25 20:30

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=55)),
                ('employee_access_code', models.CharField(max_length=25)),
                ('employee_document', models.IntegerField()),
                ('employee_gender', models.IntegerField()),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_zipcode', models.CharField(max_length=25)),
                ('employee_birth', models.DateField(blank=True, default='')),
                ('employee_parents', models.CharField(max_length=55)),
                ('employee_born_place', models.CharField(max_length=55)),
                ('employee_start_date', models.DateField(blank=True, default='')),
                ('employee_department', models.IntegerField()),
                ('employee_function', models.IntegerField()),
                ('employee_salary', models.FloatField()),
                ('employee_marital_status', models.IntegerField()),
                ('employee_photo', models.ImageField(upload_to='')),
                ('department_id', models.IntegerField()),
                ('function_id', models.IntegerField()),
                ('marital_status_id', models.IntegerField()),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to=employee.models.upload_employee_image)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('marital_status_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('marital_status_description', models.CharField(max_length=23)),
            ],
        ),
    ]
