# Generated by Django 5.1.3 on 2024-11-23 21:34

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=55)),
                ('book_author', models.CharField(max_length=55)),
                ('book_release_year', models.DateField()),
                ('book_state', models.CharField(max_length=15)),
                ('book_pages', models.IntegerField()),
                ('book_publishing_company', models.CharField(max_length=55)),
                ('book_create_at', models.DateField(auto_now_add=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to=book.models.upload_book_image)),
            ],
        ),
        migrations.CreateModel(
            name='BookStorage',
            fields=[
                ('book_storage_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('book_storage_title', models.CharField(max_length=55)),
                ('book_storage_author', models.CharField(max_length=55)),
                ('book_storage_release_year', models.DateField()),
                ('book_storage_state', models.CharField(max_length=15)),
                ('book_storage_pages', models.IntegerField()),
                ('book_storage_publishing_company', models.CharField(max_length=55)),
                ('book_storage_create_at', models.DateField(auto_now_add=True)),
                ('book_storage_quantity', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('book_storage_image', models.ImageField(blank=True, null=True, upload_to=book.models.upload_book_storage_image)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('condition_description', models.CharField(max_length=25)),
                ('sale_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('customer_surname', models.CharField(max_length=55)),
                ('customer_location', models.CharField(max_length=25)),
                ('employee_zipcode', models.CharField(max_length=25)),
                ('employee_birth', models.DateField(blank=True, default='')),
                ('customer_address', models.CharField(max_length=150)),
                ('customer_job_type', models.CharField(max_length=35)),
                ('customer_create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=55)),
                ('employee_access_code', models.CharField(max_length=25)),
                ('employee_document', models.IntegerField()),
                ('employee_gender', models.IntegerField()),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_zipcode', models.CharField(max_length=25)),
                ('employee_birth', models.DateField(blank=True, default='')),
                ('employee_parents', models.CharField(max_length=55)),
                ('employee_born_place', models.CharField(max_length=55)),
                ('employee_start_date', models.DateField(blank=True, default='')),
                ('employee_department', models.IntegerField()),
                ('employee_function', models.IntegerField()),
                ('employee_salary', models.FloatField()),
                ('employee_marital_status', models.IntegerField()),
                ('employee_photo', models.ImageField(upload_to='')),
                ('department_id', models.IntegerField()),
                ('function_id', models.IntegerField()),
                ('marital_status_id', models.IntegerField()),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to=book.models.upload_employee_image)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('marital_status_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('marital_status_description', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('payment_method_description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rent_date', models.DateField(blank=True, default='')),
                ('rent_invoice', models.CharField(max_length=25)),
                ('rent_product', models.CharField(max_length=55)),
                ('rent_amount_product', models.FloatField()),
                ('rent_payment_method', models.IntegerField()),
                ('rent_condition', models.IntegerField()),
                ('rent_descount', models.FloatField()),
                ('rent_taxes', models.FloatField()),
                ('rent_employee_commission', models.FloatField(blank=True, default='')),
                ('rent_start_date', models.DateField(blank=True, default='')),
                ('rent_end_date', models.DateField(blank=True, default='')),
                ('book_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('condition_id', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField(blank=True, default='')),
                ('sale_invoice', models.CharField(max_length=25)),
                ('sale_product', models.CharField(max_length=55)),
                ('sale_amount_product', models.FloatField()),
                ('sale_payment_method', models.IntegerField()),
                ('sale_condition', models.IntegerField()),
                ('sale_descount', models.FloatField()),
                ('sale_taxes', models.FloatField()),
                ('employee_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('condition_id', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
                ('sale_employee_commission', models.FloatField(blank=True, default='')),
            ],
        ),
    ]
