# Generated by Django 5.1.3 on 2024-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('condition_description', models.CharField(max_length=25)),
                ('sale_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('payment_method_description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField(blank=True, default='')),
                ('sale_invoice', models.CharField(max_length=25)),
                ('sale_product', models.CharField(max_length=55)),
                ('sale_amount_product', models.FloatField()),
                ('sale_payment_method', models.IntegerField()),
                ('sale_condition', models.IntegerField()),
                ('sale_descount', models.FloatField()),
                ('sale_taxes', models.FloatField()),
                ('employee_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('condition_id', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
                ('sale_employee_commission', models.FloatField(blank=True, default='')),
            ],
        ),
    ]
